// <auto-generated />
using GeekShopping.ProductApi.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductApi.Migrations
{
    [DbContext(typeof(MySqlContext))]
    [Migration("20220409211957_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductApi.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryName = "Categoria A",
                            Description = "Descrição A",
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/004.png",
                            Name = "Produto A",
                            Price = 10.1m
                        },
                        new
                        {
                            Id = 2L,
                            CategoryName = "Categoria B",
                            Description = "Descrição B",
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/001.png",
                            Name = "Produto B",
                            Price = 20.2m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Categoria C",
                            Description = "Descrição C",
                            ImageUrl = "https://assets.pokemon.com/assets/cms2/img/pokedex/full/007.png",
                            Name = "Produto C",
                            Price = 30.3m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
